
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Company
{

    public Company()
    {

        this.User = new HashSet<User>();

        this.ContactState = new HashSet<ContactState>();

    }


    public decimal Id { get; set; }

    public string TenCongTy { get; set; }

    public Nullable<decimal> SoLuongUser { get; set; }



    public virtual ICollection<User> User { get; set; }

    public virtual ICollection<ContactState> ContactState { get; set; }

}

}
