//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactStateChange
    {
        public decimal Id { get; set; }
        public Nullable<decimal> IdContact { get; set; }
        public Nullable<decimal> IdContactSate { get; set; }
        public Nullable<System.DateTime> NgayChuyenTrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> IsDangChamSoc { get; set; }
        public Nullable<bool> IsTrangThaiHienTai { get; set; }
        public Nullable<decimal> IdNguoiChuyenTrangThai { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ContactState ContactState { get; set; }
        public virtual ContactStateChange ContactStateChange1 { get; set; }
        public virtual ContactStateChange ContactStateChange2 { get; set; }
        public virtual User User { get; set; }
    }
}
