//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactStateProcess
    {
        public decimal Id { get; set; }
        public Nullable<decimal> IdTrangThaiTruoc { get; set; }
        public Nullable<decimal> IdTrangThaiSau { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ContactState ContactState { get; set; }
        public virtual ContactState ContactState1 { get; set; }
    }
}
