//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.ContractContactRoles = new HashSet<ContractContactRole>();
            this.Orders = new HashSet<Order>();
            this.Quotes = new HashSet<Quote>();
        }
    
        public decimal Id { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<decimal> SoHopDong { get; set; }
        public string NoiDung { get; set; }
        public Nullable<decimal> IdAccount { get; set; }
        public Nullable<decimal> IdLoaiContract { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TuDien TuDien { get; set; }
        public virtual ICollection<ContractContactRole> ContractContactRoles { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
