

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class CrmEntities : DbContext
{
    public CrmEntities()
        : base("name=CrmEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AccountContactRole> AccountContactRole { get; set; }

    public virtual DbSet<Action> Action { get; set; }

    public virtual DbSet<Company> Company { get; set; }

    public virtual DbSet<Contact> Contact { get; set; }

    public virtual DbSet<ContactStateChange> ContactStateChange { get; set; }

    public virtual DbSet<ContactStateProcess> ContactStateProcess { get; set; }

    public virtual DbSet<ContractContactRole> ContractContactRole { get; set; }

    public virtual DbSet<LoaiTuDien> LoaiTuDien { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<Quote> Quote { get; set; }

    public virtual DbSet<Task> Task { get; set; }

    public virtual DbSet<ToBeConverted> ToBeConverted { get; set; }

    public virtual DbSet<TuDien> TuDien { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserContactRole> UserContactRole { get; set; }

    public virtual DbSet<UserGroup> UserGroups { get; set; }

    public virtual DbSet<sysdiagram> sysdiagram { get; set; }

    public virtual DbSet<Account> Account { get; set; }

    public virtual DbSet<ContactState> ContactState { get; set; }

    public virtual DbSet<Contract> Contract { get; set; }

    public virtual DbSet<V_TASK> V_TASK { get; set; }

    public virtual DbSet<V_ACCOUNT> V_ACCOUNT { get; set; }

    public virtual DbSet<ContactProductRole> ContactProductRole { get; set; }

    public virtual DbSet<V_CONTRACT> V_CONTRACT { get; set; }


    public virtual int pr_Contact_Delete(Nullable<decimal> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Contact_Delete", idParameter);
    }


    public virtual int pr_Contact_Insert(string ho, string ten, string diaChi, Nullable<bool> gioiTinh, string image, string facebook, string skype, Nullable<System.DateTime> ngaySinh, string sdt01, string sdt02, string maSoThue, string soTaiKhoan, string website, string email, Nullable<System.DateTime> hanKhachHang, Nullable<decimal> idLoaiKhachHang, Nullable<decimal> idTrangThaiHienTai, ObjectParameter id, Nullable<decimal> idAccount)
    {

        var hoParameter = ho != null ?
            new ObjectParameter("Ho", ho) :
            new ObjectParameter("Ho", typeof(string));


        var tenParameter = ten != null ?
            new ObjectParameter("Ten", ten) :
            new ObjectParameter("Ten", typeof(string));


        var diaChiParameter = diaChi != null ?
            new ObjectParameter("DiaChi", diaChi) :
            new ObjectParameter("DiaChi", typeof(string));


        var gioiTinhParameter = gioiTinh.HasValue ?
            new ObjectParameter("GioiTinh", gioiTinh) :
            new ObjectParameter("GioiTinh", typeof(bool));


        var imageParameter = image != null ?
            new ObjectParameter("Image", image) :
            new ObjectParameter("Image", typeof(string));


        var facebookParameter = facebook != null ?
            new ObjectParameter("Facebook", facebook) :
            new ObjectParameter("Facebook", typeof(string));


        var skypeParameter = skype != null ?
            new ObjectParameter("Skype", skype) :
            new ObjectParameter("Skype", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var sdt01Parameter = sdt01 != null ?
            new ObjectParameter("Sdt01", sdt01) :
            new ObjectParameter("Sdt01", typeof(string));


        var sdt02Parameter = sdt02 != null ?
            new ObjectParameter("Sdt02", sdt02) :
            new ObjectParameter("Sdt02", typeof(string));


        var maSoThueParameter = maSoThue != null ?
            new ObjectParameter("MaSoThue", maSoThue) :
            new ObjectParameter("MaSoThue", typeof(string));


        var soTaiKhoanParameter = soTaiKhoan != null ?
            new ObjectParameter("SoTaiKhoan", soTaiKhoan) :
            new ObjectParameter("SoTaiKhoan", typeof(string));


        var websiteParameter = website != null ?
            new ObjectParameter("Website", website) :
            new ObjectParameter("Website", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        var hanKhachHangParameter = hanKhachHang.HasValue ?
            new ObjectParameter("HanKhachHang", hanKhachHang) :
            new ObjectParameter("HanKhachHang", typeof(System.DateTime));


        var idLoaiKhachHangParameter = idLoaiKhachHang.HasValue ?
            new ObjectParameter("IdLoaiKhachHang", idLoaiKhachHang) :
            new ObjectParameter("IdLoaiKhachHang", typeof(decimal));


        var idTrangThaiHienTaiParameter = idTrangThaiHienTai.HasValue ?
            new ObjectParameter("IdTrangThaiHienTai", idTrangThaiHienTai) :
            new ObjectParameter("IdTrangThaiHienTai", typeof(decimal));


        var idAccountParameter = idAccount.HasValue ?
            new ObjectParameter("IdAccount", idAccount) :
            new ObjectParameter("IdAccount", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Contact_Insert", hoParameter, tenParameter, diaChiParameter, gioiTinhParameter, imageParameter, facebookParameter, skypeParameter, ngaySinhParameter, sdt01Parameter, sdt02Parameter, maSoThueParameter, soTaiKhoanParameter, websiteParameter, emailParameter, hanKhachHangParameter, idLoaiKhachHangParameter, idTrangThaiHienTaiParameter, id, idAccountParameter);
    }


    public virtual int pr_Contact_Update(Nullable<decimal> id, string ho, string ten, string diaChi, Nullable<bool> gioiTinh, string image, string facebook, string skype, Nullable<System.DateTime> ngaySinh, string sdt01, string sdt02, string maSoThue, string soTaiKhoan, string website, string email, Nullable<System.DateTime> hanKhachHang, Nullable<decimal> idLoaiKhachHang, Nullable<decimal> idTrangThaiHienTai, Nullable<decimal> idAccount)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(decimal));


        var hoParameter = ho != null ?
            new ObjectParameter("Ho", ho) :
            new ObjectParameter("Ho", typeof(string));


        var tenParameter = ten != null ?
            new ObjectParameter("Ten", ten) :
            new ObjectParameter("Ten", typeof(string));


        var diaChiParameter = diaChi != null ?
            new ObjectParameter("DiaChi", diaChi) :
            new ObjectParameter("DiaChi", typeof(string));


        var gioiTinhParameter = gioiTinh.HasValue ?
            new ObjectParameter("GioiTinh", gioiTinh) :
            new ObjectParameter("GioiTinh", typeof(bool));


        var imageParameter = image != null ?
            new ObjectParameter("Image", image) :
            new ObjectParameter("Image", typeof(string));


        var facebookParameter = facebook != null ?
            new ObjectParameter("Facebook", facebook) :
            new ObjectParameter("Facebook", typeof(string));


        var skypeParameter = skype != null ?
            new ObjectParameter("Skype", skype) :
            new ObjectParameter("Skype", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var sdt01Parameter = sdt01 != null ?
            new ObjectParameter("Sdt01", sdt01) :
            new ObjectParameter("Sdt01", typeof(string));


        var sdt02Parameter = sdt02 != null ?
            new ObjectParameter("Sdt02", sdt02) :
            new ObjectParameter("Sdt02", typeof(string));


        var maSoThueParameter = maSoThue != null ?
            new ObjectParameter("MaSoThue", maSoThue) :
            new ObjectParameter("MaSoThue", typeof(string));


        var soTaiKhoanParameter = soTaiKhoan != null ?
            new ObjectParameter("SoTaiKhoan", soTaiKhoan) :
            new ObjectParameter("SoTaiKhoan", typeof(string));


        var websiteParameter = website != null ?
            new ObjectParameter("Website", website) :
            new ObjectParameter("Website", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        var hanKhachHangParameter = hanKhachHang.HasValue ?
            new ObjectParameter("HanKhachHang", hanKhachHang) :
            new ObjectParameter("HanKhachHang", typeof(System.DateTime));


        var idLoaiKhachHangParameter = idLoaiKhachHang.HasValue ?
            new ObjectParameter("IdLoaiKhachHang", idLoaiKhachHang) :
            new ObjectParameter("IdLoaiKhachHang", typeof(decimal));


        var idTrangThaiHienTaiParameter = idTrangThaiHienTai.HasValue ?
            new ObjectParameter("IdTrangThaiHienTai", idTrangThaiHienTai) :
            new ObjectParameter("IdTrangThaiHienTai", typeof(decimal));


        var idAccountParameter = idAccount.HasValue ?
            new ObjectParameter("IdAccount", idAccount) :
            new ObjectParameter("IdAccount", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Contact_Update", idParameter, hoParameter, tenParameter, diaChiParameter, gioiTinhParameter, imageParameter, facebookParameter, skypeParameter, ngaySinhParameter, sdt01Parameter, sdt02Parameter, maSoThueParameter, soTaiKhoanParameter, websiteParameter, emailParameter, hanKhachHangParameter, idLoaiKhachHangParameter, idTrangThaiHienTaiParameter, idAccountParameter);
    }


    public virtual int pr_Contract_Delete(Nullable<decimal> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Contract_Delete", idParameter);
    }


    public virtual int pr_Contract_Insert(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc, string soHopDong, string noiDung, Nullable<decimal> idAccount, Nullable<decimal> idLoaiContract, Nullable<decimal> idUser, ObjectParameter id)
    {

        var ngayBatDauParameter = ngayBatDau.HasValue ?
            new ObjectParameter("NgayBatDau", ngayBatDau) :
            new ObjectParameter("NgayBatDau", typeof(System.DateTime));


        var ngayKetThucParameter = ngayKetThuc.HasValue ?
            new ObjectParameter("NgayKetThuc", ngayKetThuc) :
            new ObjectParameter("NgayKetThuc", typeof(System.DateTime));


        var soHopDongParameter = soHopDong != null ?
            new ObjectParameter("SoHopDong", soHopDong) :
            new ObjectParameter("SoHopDong", typeof(string));


        var noiDungParameter = noiDung != null ?
            new ObjectParameter("NoiDung", noiDung) :
            new ObjectParameter("NoiDung", typeof(string));


        var idAccountParameter = idAccount.HasValue ?
            new ObjectParameter("IdAccount", idAccount) :
            new ObjectParameter("IdAccount", typeof(decimal));


        var idLoaiContractParameter = idLoaiContract.HasValue ?
            new ObjectParameter("IdLoaiContract", idLoaiContract) :
            new ObjectParameter("IdLoaiContract", typeof(decimal));


        var idUserParameter = idUser.HasValue ?
            new ObjectParameter("IdUser", idUser) :
            new ObjectParameter("IdUser", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Contract_Insert", ngayBatDauParameter, ngayKetThucParameter, soHopDongParameter, noiDungParameter, idAccountParameter, idLoaiContractParameter, idUserParameter, id);
    }


    public virtual int pr_Contract_Update(Nullable<decimal> id, Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc, string soHopDong, string noiDung, Nullable<decimal> idAccount, Nullable<decimal> idLoaiContract, Nullable<decimal> idUser)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(decimal));


        var ngayBatDauParameter = ngayBatDau.HasValue ?
            new ObjectParameter("NgayBatDau", ngayBatDau) :
            new ObjectParameter("NgayBatDau", typeof(System.DateTime));


        var ngayKetThucParameter = ngayKetThuc.HasValue ?
            new ObjectParameter("NgayKetThuc", ngayKetThuc) :
            new ObjectParameter("NgayKetThuc", typeof(System.DateTime));


        var soHopDongParameter = soHopDong != null ?
            new ObjectParameter("SoHopDong", soHopDong) :
            new ObjectParameter("SoHopDong", typeof(string));


        var noiDungParameter = noiDung != null ?
            new ObjectParameter("NoiDung", noiDung) :
            new ObjectParameter("NoiDung", typeof(string));


        var idAccountParameter = idAccount.HasValue ?
            new ObjectParameter("IdAccount", idAccount) :
            new ObjectParameter("IdAccount", typeof(decimal));


        var idLoaiContractParameter = idLoaiContract.HasValue ?
            new ObjectParameter("IdLoaiContract", idLoaiContract) :
            new ObjectParameter("IdLoaiContract", typeof(decimal));


        var idUserParameter = idUser.HasValue ?
            new ObjectParameter("IdUser", idUser) :
            new ObjectParameter("IdUser", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Contract_Update", idParameter, ngayBatDauParameter, ngayKetThucParameter, soHopDongParameter, noiDungParameter, idAccountParameter, idLoaiContractParameter, idUserParameter);
    }


    public virtual int pr_Task_Delete(Nullable<decimal> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Task_Delete", idParameter);
    }


    public virtual int pr_Task_Insert(Nullable<System.DateTime> taiNgay, Nullable<decimal> idUser, string lamGi, Nullable<decimal> idAccount, Nullable<decimal> idContact, Nullable<decimal> idPriority, Nullable<decimal> idStatus, Nullable<decimal> idLoaiAction, Nullable<System.DateTime> duKienHoanThanh, string tenCongViec, ObjectParameter id)
    {

        var taiNgayParameter = taiNgay.HasValue ?
            new ObjectParameter("TaiNgay", taiNgay) :
            new ObjectParameter("TaiNgay", typeof(System.DateTime));


        var idUserParameter = idUser.HasValue ?
            new ObjectParameter("IdUser", idUser) :
            new ObjectParameter("IdUser", typeof(decimal));


        var lamGiParameter = lamGi != null ?
            new ObjectParameter("LamGi", lamGi) :
            new ObjectParameter("LamGi", typeof(string));


        var idAccountParameter = idAccount.HasValue ?
            new ObjectParameter("IdAccount", idAccount) :
            new ObjectParameter("IdAccount", typeof(decimal));


        var idContactParameter = idContact.HasValue ?
            new ObjectParameter("IdContact", idContact) :
            new ObjectParameter("IdContact", typeof(decimal));


        var idPriorityParameter = idPriority.HasValue ?
            new ObjectParameter("IdPriority", idPriority) :
            new ObjectParameter("IdPriority", typeof(decimal));


        var idStatusParameter = idStatus.HasValue ?
            new ObjectParameter("IdStatus", idStatus) :
            new ObjectParameter("IdStatus", typeof(decimal));


        var idLoaiActionParameter = idLoaiAction.HasValue ?
            new ObjectParameter("IdLoaiAction", idLoaiAction) :
            new ObjectParameter("IdLoaiAction", typeof(decimal));


        var duKienHoanThanhParameter = duKienHoanThanh.HasValue ?
            new ObjectParameter("DuKienHoanThanh", duKienHoanThanh) :
            new ObjectParameter("DuKienHoanThanh", typeof(System.DateTime));


        var tenCongViecParameter = tenCongViec != null ?
            new ObjectParameter("TenCongViec", tenCongViec) :
            new ObjectParameter("TenCongViec", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Task_Insert", taiNgayParameter, idUserParameter, lamGiParameter, idAccountParameter, idContactParameter, idPriorityParameter, idStatusParameter, idLoaiActionParameter, duKienHoanThanhParameter, tenCongViecParameter, id);
    }


    public virtual int pr_Task_Update(Nullable<decimal> id, Nullable<System.DateTime> taiNgay, Nullable<decimal> idUser, string lamGi, Nullable<decimal> idAccount, Nullable<decimal> idContact, Nullable<decimal> idPriority, Nullable<decimal> idStatus, Nullable<decimal> idLoaiAction, Nullable<System.DateTime> duKienHoanThanh, string tenCongViec)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(decimal));


        var taiNgayParameter = taiNgay.HasValue ?
            new ObjectParameter("TaiNgay", taiNgay) :
            new ObjectParameter("TaiNgay", typeof(System.DateTime));


        var idUserParameter = idUser.HasValue ?
            new ObjectParameter("IdUser", idUser) :
            new ObjectParameter("IdUser", typeof(decimal));


        var lamGiParameter = lamGi != null ?
            new ObjectParameter("LamGi", lamGi) :
            new ObjectParameter("LamGi", typeof(string));


        var idAccountParameter = idAccount.HasValue ?
            new ObjectParameter("IdAccount", idAccount) :
            new ObjectParameter("IdAccount", typeof(decimal));


        var idContactParameter = idContact.HasValue ?
            new ObjectParameter("IdContact", idContact) :
            new ObjectParameter("IdContact", typeof(decimal));


        var idPriorityParameter = idPriority.HasValue ?
            new ObjectParameter("IdPriority", idPriority) :
            new ObjectParameter("IdPriority", typeof(decimal));


        var idStatusParameter = idStatus.HasValue ?
            new ObjectParameter("IdStatus", idStatus) :
            new ObjectParameter("IdStatus", typeof(decimal));


        var idLoaiActionParameter = idLoaiAction.HasValue ?
            new ObjectParameter("IdLoaiAction", idLoaiAction) :
            new ObjectParameter("IdLoaiAction", typeof(decimal));


        var duKienHoanThanhParameter = duKienHoanThanh.HasValue ?
            new ObjectParameter("DuKienHoanThanh", duKienHoanThanh) :
            new ObjectParameter("DuKienHoanThanh", typeof(System.DateTime));


        var tenCongViecParameter = tenCongViec != null ?
            new ObjectParameter("TenCongViec", tenCongViec) :
            new ObjectParameter("TenCongViec", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Task_Update", idParameter, taiNgayParameter, idUserParameter, lamGiParameter, idAccountParameter, idContactParameter, idPriorityParameter, idStatusParameter, idLoaiActionParameter, duKienHoanThanhParameter, tenCongViecParameter);
    }


    public virtual int pr_Account_Delete(Nullable<decimal> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Account_Delete", idParameter);
    }


    public virtual int pr_Account_Insert(string accountName, string diaChi, string sdt01, string sdt02, Nullable<decimal> idAccountType, ObjectParameter id)
    {

        var accountNameParameter = accountName != null ?
            new ObjectParameter("AccountName", accountName) :
            new ObjectParameter("AccountName", typeof(string));


        var diaChiParameter = diaChi != null ?
            new ObjectParameter("DiaChi", diaChi) :
            new ObjectParameter("DiaChi", typeof(string));


        var sdt01Parameter = sdt01 != null ?
            new ObjectParameter("Sdt01", sdt01) :
            new ObjectParameter("Sdt01", typeof(string));


        var sdt02Parameter = sdt02 != null ?
            new ObjectParameter("Sdt02", sdt02) :
            new ObjectParameter("Sdt02", typeof(string));


        var idAccountTypeParameter = idAccountType.HasValue ?
            new ObjectParameter("IdAccountType", idAccountType) :
            new ObjectParameter("IdAccountType", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Account_Insert", accountNameParameter, diaChiParameter, sdt01Parameter, sdt02Parameter, idAccountTypeParameter, id);
    }


    public virtual int pr_Account_Update(Nullable<decimal> id, string accountName, string diaChi, string sdt01, string sdt02, Nullable<decimal> idAccountType)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(decimal));


        var accountNameParameter = accountName != null ?
            new ObjectParameter("AccountName", accountName) :
            new ObjectParameter("AccountName", typeof(string));


        var diaChiParameter = diaChi != null ?
            new ObjectParameter("DiaChi", diaChi) :
            new ObjectParameter("DiaChi", typeof(string));


        var sdt01Parameter = sdt01 != null ?
            new ObjectParameter("Sdt01", sdt01) :
            new ObjectParameter("Sdt01", typeof(string));


        var sdt02Parameter = sdt02 != null ?
            new ObjectParameter("Sdt02", sdt02) :
            new ObjectParameter("Sdt02", typeof(string));


        var idAccountTypeParameter = idAccountType.HasValue ?
            new ObjectParameter("IdAccountType", idAccountType) :
            new ObjectParameter("IdAccountType", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Account_Update", idParameter, accountNameParameter, diaChiParameter, sdt01Parameter, sdt02Parameter, idAccountTypeParameter);
    }


    public virtual int pr_Contact_Update_Image(Nullable<decimal> id, string img)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(decimal));


        var imgParameter = img != null ?
            new ObjectParameter("Img", img) :
            new ObjectParameter("Img", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_Contact_Update_Image", idParameter, imgParameter);
    }


    public virtual int pr_ContractContactRole_Insert(Nullable<decimal> idContact, Nullable<decimal> idContract, Nullable<bool> isDeleted, Nullable<bool> isPrimary, ObjectParameter id)
    {

        var idContactParameter = idContact.HasValue ?
            new ObjectParameter("IdContact", idContact) :
            new ObjectParameter("IdContact", typeof(decimal));


        var idContractParameter = idContract.HasValue ?
            new ObjectParameter("IdContract", idContract) :
            new ObjectParameter("IdContract", typeof(decimal));


        var isDeletedParameter = isDeleted.HasValue ?
            new ObjectParameter("IsDeleted", isDeleted) :
            new ObjectParameter("IsDeleted", typeof(bool));


        var isPrimaryParameter = isPrimary.HasValue ?
            new ObjectParameter("IsPrimary", isPrimary) :
            new ObjectParameter("IsPrimary", typeof(bool));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_ContractContactRole_Insert", idContactParameter, idContractParameter, isDeletedParameter, isPrimaryParameter, id);
    }


    public virtual int pr_ContractContactRole_Update(Nullable<decimal> idContact, Nullable<decimal> idContract, Nullable<bool> isDeleted, Nullable<bool> isPrimary)
    {

        var idContactParameter = idContact.HasValue ?
            new ObjectParameter("IdContact", idContact) :
            new ObjectParameter("IdContact", typeof(decimal));


        var idContractParameter = idContract.HasValue ?
            new ObjectParameter("IdContract", idContract) :
            new ObjectParameter("IdContract", typeof(decimal));


        var isDeletedParameter = isDeleted.HasValue ?
            new ObjectParameter("IsDeleted", isDeleted) :
            new ObjectParameter("IsDeleted", typeof(bool));


        var isPrimaryParameter = isPrimary.HasValue ?
            new ObjectParameter("IsPrimary", isPrimary) :
            new ObjectParameter("IsPrimary", typeof(bool));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_ContractContactRole_Update", idContactParameter, idContractParameter, isDeletedParameter, isPrimaryParameter);
    }

}

}

