//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrmEntities : DbContext
    {
        public CrmEntities()
            : base("name=CrmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountContactRole> AccountContactRoles { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactState> ContactStates { get; set; }
        public virtual DbSet<ContactStateChange> ContactStateChanges { get; set; }
        public virtual DbSet<ContactStateProcess> ContactStateProcesses { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<ContractContactRole> ContractContactRoles { get; set; }
        public virtual DbSet<LoaiTuDien> LoaiTuDiens { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<ToBeConverted> ToBeConverteds { get; set; }
        public virtual DbSet<TuDien> TuDiens { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserContactRole> UserContactRoles { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
    }
}
