

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CrmEntities : DbContext
{
    public CrmEntities()
        : base("name=CrmEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Account> Account { get; set; }

    public virtual DbSet<AccountContactRole> AccountContactRole { get; set; }

    public virtual DbSet<Action> Action { get; set; }

    public virtual DbSet<Company> Companie { get; set; }

    public virtual DbSet<Contact> Contact { get; set; }

    public virtual DbSet<ContactState> ContactState { get; set; }

    public virtual DbSet<ContactStateChange> ContactStateChange { get; set; }

    public virtual DbSet<ContactStateProcess> ContactStateProcess { get; set; }

    public virtual DbSet<Contract> Contract { get; set; }

    public virtual DbSet<ContractContactRole> ContractContactRole { get; set; }

    public virtual DbSet<LoaiTuDien> LoaiTuDien { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<Quote> Quote { get; set; }

    public virtual DbSet<Task> Task { get; set; }

    public virtual DbSet<ToBeConverted> ToBeConverted { get; set; }

    public virtual DbSet<TuDien> TuDien { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserContactRole> UserContactRole { get; set; }

    public virtual DbSet<UserGroup> UserGroup { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

}

}

