
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public Product()
    {

        this.ContactProductRole = new HashSet<ContactProductRole>();

    }


    public decimal Id { get; set; }

    public string ProductName { get; set; }

    public Nullable<decimal> GiaNhap { get; set; }

    public Nullable<decimal> GiaBan { get; set; }

    public Nullable<decimal> IdLoaiProduct { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual TuDien TuDien { get; set; }

    public virtual ICollection<ContactProductRole> ContactProductRole { get; set; }

}

}
