
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ToBeConverted
{

    public decimal Id { get; set; }

    public Nullable<decimal> IdContactState { get; set; }

    public string TenYeuCau { get; set; }

    public Nullable<int> ThuTuSapXep { get; set; }



    public virtual ContactState ContactState { get; set; }

}

}
