
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TuDien
{

    public TuDien()
    {

        this.Order = new HashSet<Order>();

        this.Product = new HashSet<Product>();

        this.Quote = new HashSet<Quote>();

        this.Task = new HashSet<Task>();

        this.Task1 = new HashSet<Task>();

        this.Task2 = new HashSet<Task>();

        this.Contact = new HashSet<Contact>();

        this.Account = new HashSet<Account>();

        this.Contract = new HashSet<Contract>();

    }


    public decimal Id { get; set; }

    public string TenTuDien { get; set; }

    public string MaTuDien { get; set; }

    public Nullable<decimal> IdLoaiTuDien { get; set; }

    public string GhiChu { get; set; }



    public virtual LoaiTuDien LoaiTuDien { get; set; }

    public virtual ICollection<Order> Order { get; set; }

    public virtual ICollection<Product> Product { get; set; }

    public virtual ICollection<Quote> Quote { get; set; }

    public virtual ICollection<Task> Task { get; set; }

    public virtual ICollection<Task> Task1 { get; set; }

    public virtual ICollection<Task> Task2 { get; set; }

    public virtual ICollection<Contact> Contact { get; set; }

    public virtual ICollection<Account> Account { get; set; }

    public virtual ICollection<Contract> Contract { get; set; }

}

}
