//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuDien
    {
        public TuDien()
        {
            this.Accounts = new HashSet<Account>();
            this.Contracts = new HashSet<Contract>();
            this.Orders = new HashSet<Order>();
            this.Products = new HashSet<Product>();
            this.Quotes = new HashSet<Quote>();
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
            this.Tasks2 = new HashSet<Task>();
        }
    
        public decimal Id { get; set; }
        public string TenTuDien { get; set; }
        public string MaTuDien { get; set; }
        public Nullable<decimal> IdLoaiTuDien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual LoaiTuDien LoaiTuDien { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task> Tasks1 { get; set; }
        public virtual ICollection<Task> Tasks2 { get; set; }
    }
}
