//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_CRM2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.Actions = new HashSet<Action>();
            this.Users = new HashSet<User>();
        }
    
        public decimal Id { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
