
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserGroup
{

    public UserGroup()
    {

        this.Action = new HashSet<Action>();

        this.User = new HashSet<User>();

    }


    public decimal Id { get; set; }

    public string GroupName { get; set; }

    public Nullable<decimal> IdCompany { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<decimal> Order { get; set; }



    public virtual ICollection<Action> Action { get; set; }

    public virtual ICollection<User> User { get; set; }

    public virtual Company Company { get; set; }

}

}
