
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class V_ACCOUNT
{

    public decimal Id { get; set; }

    public string AccountName { get; set; }

    public string DiaChi { get; set; }

    public string Sdt01 { get; set; }

    public string Sdt02 { get; set; }

    public Nullable<decimal> IdAccountType { get; set; }

    public string TenTuDien { get; set; }

}

}
