
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class V_CONTRACT
{

    public decimal Id { get; set; }

    public Nullable<System.DateTime> NgayBatDau { get; set; }

    public Nullable<System.DateTime> NgayKetThuc { get; set; }

    public string SoHopDong { get; set; }

    public string NoiDung { get; set; }

    public Nullable<decimal> IdAccount { get; set; }

    public Nullable<decimal> IdLoaiContract { get; set; }

    public Nullable<decimal> IdUser { get; set; }

    public string Ho { get; set; }

    public string Ten { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

}

}
