
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BKI_CRM2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class V_TASK
{

    public decimal Id { get; set; }

    public Nullable<System.DateTime> TaiNgay { get; set; }

    public Nullable<decimal> IdUser { get; set; }

    public string LamGi { get; set; }

    public Nullable<decimal> IdAccount { get; set; }

    public Nullable<decimal> IdContact { get; set; }

    public Nullable<decimal> IdStatus { get; set; }

    public Nullable<decimal> IdLoaiAction { get; set; }

    public Nullable<System.DateTime> DuKienHoanThanh { get; set; }

    public string TenCongViec { get; set; }

    public string AccountName { get; set; }

    public string TenTuDien { get; set; }

    public string Ho { get; set; }

    public string Ten { get; set; }

    public string UserName { get; set; }

    public string TrangThai { get; set; }

    public string MucUuTien { get; set; }

    public Nullable<decimal> IdPriority { get; set; }

}

}
